// Optical F5Low's compute shaders, compiled ahead of time: this both writes and checks
// OptiScaler/native/F5LowShaderBytecode.h, so the game never compiles them (a compile on the present thread or in a
// bind hook is a hitch).
//
//   cl /std:c++20 /EHsc /W4 tests\nr_shader_bytecode_smoke.cpp d3dcompiler.lib
//   nr_shader_bytecode_smoke.exe                     checks the embedded bytecode is what the sources compile to now
//   nr_shader_bytecode_smoke.exe --write <header>    writes it (after changing a shader)
//
// The same compiler, flags, entry points and macros the runtime used to compile with (d3dcompiler_47, cs_5_0, O3).
#include <windows.h>
#include <d3dcompiler.h>

#include "../OptiScaler/motion/OpticalFlow_Hlsl.h"
#include "../OptiScaler/motion/TrustMask_Hlsl.h"
#include "../OptiScaler/native/DepthCopyDx11_Hlsl.h"
#include "../OptiScaler/native/DepthResolve_Hlsl.h"

#if __has_include("../OptiScaler/native/F5LowShaderBytecode.h")
#include "../OptiScaler/native/F5LowShaderBytecode.h"
#define HAVE_BYTECODE 1
#endif

#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace
{
struct Item
{
    const char* group;      // the key's first part, and the source name given to the compiler
    const char* sourceName; // what the runtime passed as pSourceName
    const char* source;
    const char* entry;
    const char* lumaMode; // "" for none, else LUMA_MODE's value
};

const Item kItems[] = {
    { "OpticalFlow", "OpticalFlow", OpticalFlowHlsl::kSource, "Luma", "" },
    { "OpticalFlow", "OpticalFlow", OpticalFlowHlsl::kSource, "Down", "" },
    { "OpticalFlow", "OpticalFlow", OpticalFlowHlsl::kSource, "Match", "" },
    { "OpticalFlow", "OpticalFlow", OpticalFlowHlsl::kSource, "Median", "" },
    { "OpticalFlow", "OpticalFlow", OpticalFlowHlsl::kSource, "Smooth", "" },
    { "OpticalFlow", "OpticalFlow", OpticalFlowHlsl::kSource, "Visualise", "" },
    { "OpticalFlow", "OpticalFlow", OpticalFlowHlsl::kSource, "Global", "" },
    { "OpticalFlow", "OpticalFlow", OpticalFlowHlsl::kSource, "Luma", "1" },
    { "OpticalFlow", "OpticalFlow", OpticalFlowHlsl::kSource, "Luma", "2" },
    { "OpticalFlow", "OpticalFlow", OpticalFlowHlsl::kSource, "Luma", "3" },
    { "OpticalFlowScene", "OpticalFlow", OpticalFlowHlsl::kSceneSource, "SceneHist", "" },
    { "OpticalFlowScene", "OpticalFlow", OpticalFlowHlsl::kSceneSource, "SceneDiverge", "" },
    { "TrustMask", "TrustMask", TrustMaskHlsl::kSource, "DepthProxy", "" },
    { "TrustMask", "TrustMask", TrustMaskHlsl::kSource, "ClearCounter", "" },
    { "TrustMask", "TrustMask", TrustMaskHlsl::kSource, "Trust", "" },
    { "TrustMask", "TrustMask", TrustMaskHlsl::kSource, "CopyFlow", "" },
    { "TrustMask", "TrustMask", TrustMaskHlsl::kSource, "GuideDepth", "" },
    { "TrustMask", "TrustMask", TrustMaskHlsl::kSource, "GuideMotion", "" },
    { "DepthCopy", "DepthCopy", DepthCopyDx11Hlsl::kConvertSource, "CSMain", "" },
    { "DepthResolve", "DepthResolve", DepthResolveHlsl::kSource, "NearestReversed", "" },
    { "DepthResolve", "DepthResolve", DepthResolveHlsl::kSource, "NearestStandard", "" },
};

bool Compile(const Item& item, std::vector<unsigned char>& out)
{
    const D3D_SHADER_MACRO macros[] = { { "LUMA_MODE", item.lumaMode }, { nullptr, nullptr } };
    ID3DBlob* code = nullptr;
    ID3DBlob* messages = nullptr;

    const HRESULT hr =
        D3DCompile(item.source, strlen(item.source), item.sourceName, item.lumaMode[0] != '\0' ? macros : nullptr,
                   nullptr, item.entry, "cs_5_0", D3DCOMPILE_OPTIMIZATION_LEVEL3, 0, &code, &messages);

    if (FAILED(hr))
    {
        printf("compiling %s %s %s: %s\n", item.group, item.entry, item.lumaMode,
               messages != nullptr ? (const char*) messages->GetBufferPointer() : "no message");

        if (messages != nullptr)
            messages->Release();

        return false;
    }

    if (messages != nullptr)
        messages->Release();

    const auto* bytes = (const unsigned char*) code->GetBufferPointer();
    out.assign(bytes, bytes + code->GetBufferSize());
    code->Release();
    return true;
}

std::string ArrayName(const Item& item)
{
    return std::string(item.group) + "_" + item.entry +
           (item.lumaMode[0] != '\0' ? std::string("_") + item.lumaMode : "");
}

int Write(const char* path)
{
    std::string text;
    text += "#pragma once\n\n";
    text += "// Generated by tests/nr_shader_bytecode_smoke.cpp --write from motion/OpticalFlow_Hlsl.h,\n";
    text += "// motion/TrustMask_Hlsl.h, native/DepthCopyDx11_Hlsl.h and native/DepthResolve_Hlsl.h (cs_5_0, O3).\n";
    text += "// Do not edit; regenerate.\n\n";
    text += "#include <cstddef>\n#include <cstring>\n\nnamespace F5LowShaderBytecode\n{\n";

    for (const Item& item : kItems)
    {
        std::vector<unsigned char> code;

        if (!Compile(item, code))
            return 1;

        text += "inline constexpr unsigned char " + ArrayName(item) + "[] = {";

        for (size_t i = 0; i < code.size(); ++i)
        {
            char byte[16];
            snprintf(byte, sizeof(byte), "%s0x%02x", i % 20 == 0 ? "\n    " : " ", code[i]);
            text += byte;
            text += i + 1 < code.size() ? "," : "";
        }

        text += "\n};\n\n";
    }

    text += "struct Shader\n{\n    const char* group;\n    const char* entry;\n    const char* lumaMode;\n"
            "    const unsigned char* code;\n    size_t size;\n\n"
            "    // Shaped like the ID3DBlob a compile returned, so the callers' code stays as it was\n"
            "    const void* GetBufferPointer() const { return code; }\n"
            "    size_t GetBufferSize() const { return size; }\n    void Release() const {}\n};\n\n";
    text += "inline constexpr Shader kShaders[] = {\n";

    for (const Item& item : kItems)
        text += std::string("    { \"") + item.group + "\", \"" + item.entry + "\", \"" + item.lumaMode + "\", " +
                ArrayName(item) + ", sizeof(" + ArrayName(item) + ") },\n";

    text += "};\n\n";
    text += "// The bytecode of `entry` in `group`, built with LUMA_MODE `lumaMode` (\"\" for none); null if there is "
            "none.\n";
    text += "inline const Shader* Find(const char* group, const char* entry, const char* lumaMode = \"\")\n{\n"
            "    for (const Shader& shader : kShaders)\n"
            "    {\n"
            "        if (strcmp(shader.group, group) == 0 && strcmp(shader.entry, entry) == 0 &&\n"
            "            strcmp(shader.lumaMode, lumaMode) == 0)\n"
            "            return &shader;\n"
            "    }\n\n"
            "    return nullptr;\n}\n} // namespace F5LowShaderBytecode\n";

    FILE* file = nullptr;

    if (fopen_s(&file, path, "wb") != 0 || file == nullptr)
    {
        printf("cannot write %s\n", path);
        return 1;
    }

    fwrite(text.data(), 1, text.size(), file);
    fclose(file);
    printf("nr_shader_bytecode_smoke: wrote %zu shaders to %s\n", sizeof(kItems) / sizeof(kItems[0]), path);
    return 0;
}

int Check()
{
#ifndef HAVE_BYTECODE
    printf("nr_shader_bytecode_smoke: FAIL, no native/F5LowShaderBytecode.h (run with --write)\n");
    return 1;
#else
    int fails = 0;

    for (const Item& item : kItems)
    {
        std::vector<unsigned char> code;

        if (!Compile(item, code))
        {
            ++fails;
            continue;
        }

        const auto* embedded = F5LowShaderBytecode::Find(item.group, item.entry, item.lumaMode);

        if (embedded == nullptr || embedded->size != code.size() ||
            memcmp(embedded->code, code.data(), code.size()) != 0)
        {
            printf("FAIL: %s is stale or missing (run with --write)\n", ArrayName(item).c_str());
            ++fails;
        }
    }

    // Nothing embedded that this list no longer has
    for (const auto& shader : F5LowShaderBytecode::kShaders)
    {
        bool listed = false;

        for (const Item& item : kItems)
            listed = listed || (strcmp(shader.group, item.group) == 0 && strcmp(shader.entry, item.entry) == 0 &&
                                strcmp(shader.lumaMode, item.lumaMode) == 0);

        if (!listed)
        {
            printf("FAIL: %s %s %s is embedded but no longer listed (run with --write)\n", shader.group, shader.entry,
                   shader.lumaMode);
            ++fails;
        }
    }

    printf(fails == 0 ? "nr_shader_bytecode_smoke: PASS\n" : "nr_shader_bytecode_smoke: %d FAIL\n", fails);
    return fails == 0 ? 0 : 1;
#endif
}
} // namespace

int main(int argc, char** argv)
{
    if (argc == 3 && strcmp(argv[1], "--write") == 0)
        return Write(argv[2]);

    return Check();
}
